/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as ContentSlidesNumberRouteImport } from './routes/content/slides/$number'
import { Route as ContentWorksheetsNumberRouteImport } from './routes/content/worksheets/$number'

const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const ContentSlidesNumberRoute = ContentSlidesNumberRouteImport.update({
  id: '/content/slides/$number',
  path: '/content/slides/$number',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentWorksheetsNumberRoute = ContentWorksheetsNumberRouteImport.update({
  id: '/content/worksheets/$number',
  path: '/content/worksheets/$number',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/content/slides/$number': typeof ContentSlidesNumberRoute
  '/content/worksheets/$number': typeof ContentWorksheetsNumberRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/content/slides/$number': typeof ContentSlidesNumberRoute
  '/content/worksheets/$number': typeof ContentWorksheetsNumberRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteRouteWithChildren
  '/_app/': typeof AppIndexRoute
  '/content/slides/$number': typeof ContentSlidesNumberRoute
  '/content/worksheets/$number': typeof ContentWorksheetsNumberRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/content/slides/$number' | '/content/worksheets/$number'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/content/slides/$number' | '/content/worksheets/$number'
  id:
    | '__root__'
    | '/_app'
    | '/_app/'
    | '/content/slides/$number'
    | '/content/worksheets/$number'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren
  ContentSlidesNumberRoute: typeof ContentSlidesNumberRoute
  ContentWorksheetsNumberRoute: typeof ContentWorksheetsNumberRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/content/slides/$number': {
      id: '/content/slides/$number'
      path: '/content/slides/$number'
      fullPath: '/content/slides/$number'
      preLoaderRoute: typeof ContentSlidesNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content/worksheets/$number': {
      id: '/content/worksheets/$number'
      path: '/content/worksheets/$number'
      fullPath: '/content/worksheets/$number'
      preLoaderRoute: typeof ContentWorksheetsNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppIndexRoute: AppIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
  ContentSlidesNumberRoute: ContentSlidesNumberRoute,
  ContentWorksheetsNumberRoute: ContentWorksheetsNumberRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
